<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
		<PackageVersion Include="ClosedXML" Version="0.105.0" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0" />
		<PackageVersion Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.0" />
	
        <!-- Code Analysis -->
        <PackageVersion Include="Meziantou.Analyzer" Version="2.0.257" />
        <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.16.0.128591" />
        <PackageVersion Include="Roslynator.Analyzers" Version="4.14.1" />
        <PackageVersion Include="xunit.analyzers" Version="1.26.0" />
    </ItemGroup>
</Project>
