// <auto-generated />
using System;
using BrewInventory.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrewInventory.App.Data.Migrations
{
    [DbContext(typeof(BrewInventoryContext))]
    [Migration("20251231145646_AddRecipeEntities")]
    partial class AddRecipeEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BrewInventory.App.Data.Entities.Fermentable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BestBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrewfatherId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Color")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Supplier")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Fermentables");
                });

            modelBuilder.Entity("BrewInventory.App.Data.Entities.Hop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AlphaAcid")
                        .HasColumnType("REAL");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BestBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrewfatherId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HarvestYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Hops");
                });

            modelBuilder.Entity("BrewInventory.App.Data.Entities.Misc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BestBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrewfatherId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Miscs");
                });

            modelBuilder.Entity("BrewInventory.App.Data.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrewfatherId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("BrewInventory.App.Data.Entities.RecipeFermentable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("FermentableId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FermentableId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeFermentables");
                });

            modelBuilder.Entity("BrewInventory.App.Data.Entities.RecipeHop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("HopId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HopId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeHops");
                });

            modelBuilder.Entity("BrewInventory.App.Data.Entities.RecipeMisc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("MiscId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MiscId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeMiscs");
                });

            modelBuilder.Entity("BrewInventory.App.Data.Entities.RecipeYeast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YeastId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("YeastId");

                    b.ToTable("RecipeYeasts");
                });

            modelBuilder.Entity("BrewInventory.App.Data.Entities.Yeast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BestBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrewfatherId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Form")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Labaratory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Yeasts");
                });

            modelBuilder.Entity("BrewInventory.App.Data.Entities.RecipeFermentable", b =>
                {
                    b.HasOne("BrewInventory.App.Data.Entities.Fermentable", "Fermentable")
                        .WithMany()
                        .HasForeignKey("FermentableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrewInventory.App.Data.Entities.Recipe", "Recipe")
                        .WithMany("RecipeFermentables")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fermentable");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BrewInventory.App.Data.Entities.RecipeHop", b =>
                {
                    b.HasOne("BrewInventory.App.Data.Entities.Hop", "Hop")
                        .WithMany()
                        .HasForeignKey("HopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrewInventory.App.Data.Entities.Recipe", "Recipe")
                        .WithMany("RecipeHops")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hop");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BrewInventory.App.Data.Entities.RecipeMisc", b =>
                {
                    b.HasOne("BrewInventory.App.Data.Entities.Misc", "Misc")
                        .WithMany()
                        .HasForeignKey("MiscId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrewInventory.App.Data.Entities.Recipe", "Recipe")
                        .WithMany("RecipeMiscs")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Misc");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BrewInventory.App.Data.Entities.RecipeYeast", b =>
                {
                    b.HasOne("BrewInventory.App.Data.Entities.Recipe", "Recipe")
                        .WithMany("RecipeYeasts")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrewInventory.App.Data.Entities.Yeast", "Yeast")
                        .WithMany()
                        .HasForeignKey("YeastId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("Yeast");
                });

            modelBuilder.Entity("BrewInventory.App.Data.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeFermentables");

                    b.Navigation("RecipeHops");

                    b.Navigation("RecipeMiscs");

                    b.Navigation("RecipeYeasts");
                });
#pragma warning restore 612, 618
        }
    }
}
