<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b1bb38a1-871e-4cca-9820-c2d0fee027f3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\**" />
    <Content Remove="Data\**" />
    <EmbeddedResource Remove="Data\**" />
    <None Remove="Data\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BrewInventory.Domain\BrewInventory.Domain.csproj" />
    <ProjectReference Include="..\BrewInventory.Application\BrewInventory.Application.csproj" />
    <ProjectReference Include="..\BrewInventory.Infrastructure\BrewInventory.Infrastructure.csproj" />
  </ItemGroup>

</Project>
